package:
  name: igblast
  version: "1.6.1"

about:
  home: http://www.ncbi.nlm.nih.gov/projects/igblast/
  license: Public Domain
  summary: A tool for analyzing immunoglobulin (IG) and T cell receptor (TR) sequences.

source:
  md5: 19b4ad3ce7165dff2ce64f5e4bd9d2ce  # [linux]
  md5: a5cf8b634ba6f6eb282411ea4d188d39  # [osx]
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.6.1/ncbi-igblast-1.6.1-x64-linux.tar.gz  # [linux]
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.6.1/ncbi-igblast-1.6.1-x64-macosx.tar.gz  # [osx]

build:
  number: 0

requirements:
  build:
    - gnu-wget
    - patchelf  # [linux]
  run:
    - perl-threaded >=5.8.8
    - libgcc  # [linux]
    - zlib
    - bzip2

test:
  commands:
    - igblastn -h
