{% set version="2.1.0" %}

package:
  name: gdrive
  version: {{ version }}

source:
  fn: gdrive-{{ version }}.tar.gz
  url: https://github.com/prasmussen/gdrive/archive/{{ version }}.tar.gz
  sha256: a1ea624e913e258596ea6340c8818a90c21962b0a75cf005e49a0f72f2077b2e

build:
  number: 0

requirements:
  build:
    - go

test:
  commands:
    - gdrive help

about:
  home: https://github.com/prasmussen/gdrive
  license: MIT
  summary: Google Drive CLI Client
